/**
 * ローマ字表記からひらがなへのコンバート（雑）
 *
 * @param {*} string ローマ字表記の文字列
 * @returns ひらがなの文字列
 * @url https://github.com/cloneko/kana2romaji
 */
function romaji2kana(string) {
  if (!string) {
    return "";
  }

  let value = string.toLowerCase() || "";

  const romajiKanaTable = [
    {
      'a"': "あ゛",
      ba: "ば",
      be: "べ",
      bi: "び",
      bo: "ぼ",
      bu: "ぶ",
      da: "だ",
      de: "で",
      di: "ぢ",
      do: "ど",
      du: "づ",
      fu: "ふ",
      ga: "が",
      ge: "げ",
      gi: "ぎ",
      go: "ご",
      gu: "ぐ",
      ha: "は",
      he: "へ",
      hi: "ひ",
      ho: "ほ",
      ja: "じゃ",
      ji: "じ",
      jo: "じょ",
      ju: "じゅ",
      ka: "か",
      ke: "け",
      ki: "き",
      ko: "こ",
      ku: "く",
      ma: "ま",
      me: "め",
      mi: "み",
      mo: "も",
      mu: "む",
      na: "な",
      ne: "ね",
      ni: "に",
      no: "の",
      nu: "ぬ",
      pa: "ぱ",
      pe: "ぺ",
      pi: "ぴ",
      po: "ぽ",
      pu: "ぷ",
      ra: "ら",
      re: "れ",
      ri: "り",
      ro: "ろ",
      ru: "る",
      sa: "さ",
      se: "せ",
      so: "そ",
      su: "す",
      ta: "た",
      ti: "ち",
      te: "て",
      to: "と",
      va: "う゛ぁ",
      ve: "う゛ぇ",
      vi: "う゛ぃ",
      vo: "う゛ぉ",
      vu: "う゛",
      vu: "う゛ぅ",
      wa: "わ",
      wo: "を",
      xa: "ぁ",
      xe: "ぇ",
      xi: "ぃ",
      xo: "ぉ",
      xu: "ぅ",
      ya: "や",
      yo: "よ",
      yu: "ゆ",
      za: "ざ",
      ze: "ぜ",
      zo: "ぞ",
      zu: "ず",
      nn: "ん",
    },
    {
      cchi: "っち",
      xtsu: "っ",
    },
    {
      bba: "っば",
      bbe: "っべ",
      bbi: "っび",
      bbo: "っぼ",
      bbu: "っぶ",
      byo: "びょ",
      byu: "びゅ",
      cha: "ちゃ",
      chi: "ち",
      cho: "ちょ",
      chu: "ちゅ",
      dda: "っだ",
      dde: "っで",
      ddi: "っぢ",
      ddo: "っど",
      ddu: "っづ",
      dha: "でゃ",
      dho: "でょ",
      dhu: "でゅ",
      dya: "ぢゃ",
      dyo: "ぢょ",
      dyu: "ぢゅ",
      ffu: "っふ",
      gga: "っが",
      gge: "っげ",
      ggi: "っぎ",
      ggo: "っご",
      ggu: "っぐ",
      gya: "ぎゃ",
      gyo: "ぎょ",
      gyu: "ぎゅ",
      hha: "っは",
      hhe: "っへ",
      hhi: "っひ",
      hho: "っほ",
      hya: "ひゃ",
      hyo: "ひょ",
      hyu: "ひゅ",
      jji: "っじ",
      kka: "っか",
      kke: "っけ",
      kki: "っき",
      kko: "っこ",
      kku: "っく",
      kya: "きゃ",
      kyo: "きょ",
      kyu: "きゅ",
      mma: "っま",
      mme: "っめ",
      mmi: "っみ",
      mmo: "っも",
      mmu: "っむ",
      mya: "みゃ",
      myo: "みょ",
      myu: "みゅ",
      nna: "っな",
      nne: "っね",
      nni: "っに",
      nno: "っの",
      nnu: "っぬ",
      nya: "にゃ",
      nyo: "にょ",
      nyu: "にゅ",
      ppa: "っぱ",
      ppe: "っぺ",
      ppi: "っぴ",
      ppo: "っぽ",
      ppu: "っぷ",
      pya: "びゃ",
      rra: "っら",
      rre: "っれ",
      rri: "っり",
      rro: "っろ",
      rru: "っる",
      rya: "りゃ",
      ryo: "りょ",
      ryu: "りゅ",
      sha: "しゃ",
      shi: "し",
      sho: "しょ",
      shu: "しゅ",
      ssa: "っさ",
      sse: "っせ",
      sshi: "っし",
      sso: "っそ",
      ssu: "っす",
      tee: "てぇ",
      tha: "てぁ",
      thi: "てぃ",
      tsu: "つ",
      tta: "った",
      tte: "って",
      tto: "っと",
      ttu: "っつ",
      wwa: "っわ",
      xya: "ゃ",
      xyo: "ょ",
      xyu: "ゅ",
      yya: "っや",
      yyo: "っよ",
      yyu: "っゆ",
      zza: "っざ",
      zze: "っぜ",
      zzo: "っぞ",
      zzu: "っず",
    },
    {
      a: "あ",
      i: "い",
      u: "う",
      e: "え",
      o: "お",
    },
    {
      "-": "ー",
      ",": "、",
      ".": "。",
    },
  ];

  let res = "";
  while (0 < value.length) {
    let isReplace = false;
    romajiKanaTable.some((list) => {
      Object.keys(list).some((romaji) => {
        if (value.startsWith(romaji)) {
          value = value.replace(romaji, "");
          res += list[romaji];
          return (isReplace = true);
        }
      });
      return isReplace;
    });

    if (!isReplace) {
      res += value.substr(0, 1);
      value = value.substr(1);
    }
  }

  return res;
}
