/**
 * ローマ字表記からひらがなへのコンバート
 *
 * @param {*} string ローマ字表記の文字列
 * @returns ひらがなの文字列
 * @url https://github.com/cloneko/kana2romaji
 */
function romaji2kana(string) {
  var value = string || "";

  const romajiKanaTable = {
    0: {
      va: "う゛ぁ",
      vi: "う゛ぃ",
      vu: "う゛ぅ",
      ve: "う゛ぇ",
      vo: "う゛ぉ",
    },
    1: {
      kya: "きゃ",
      kyu: "きゅ",
      kyo: "きょ",
      gya: "ぎゃ",
      gyu: "ぎゅ",
      gyo: "ぎょ",
      sha: "しゃ",
      shu: "しゅ",
      sho: "しょ",
      ja: "じゃ",
      ju: "じゅ",
      jo: "じょ",
      cha: "ちゃ",
      chu: "ちゅ",
      cho: "ちょ",
      dya: "ぢゃ",
      dyu: "ぢゅ",
      dyo: "ぢょ",
      dha: "でゃ",
      dhu: "でゅ",
      dho: "でょ",
      nya: "にゃ",
      nyu: "にゅ",
      nyo: "にょ",
      hya: "ひゃ",
      hyu: "ひゅ",
      hyo: "ひょ",
      pya: "びゃ",
      byu: "びゅ",
      byo: "びょ",
      mya: "みゃ",
      myu: "みゅ",
      myo: "みょ",
      rya: "りゃ",
      ryu: "りゅ",
      ryo: "りょ",
      tha: "てぁ",
      thi: "てぃ",
      tee: "てぇ",
      vu: "う゛",
      'a"': "あ゛",
      kka: "っか",
      kki: "っき",
      kku: "っく",
      kke: "っけ",
      kko: "っこ",
      ssa: "っさ",
      sshi: "っし",
      ssu: "っす",
      sse: "っせ",
      sso: "っそ",
      tta: "った",
      cchi: "っち",
      ttu: "っつ",
      tte: "って",
      tto: "っと",
      nna: "っな",
      nni: "っに",
      nnu: "っぬ",
      nne: "っね",
      nno: "っの",
      hha: "っは",
      hhi: "っひ",
      ffu: "っふ",
      hhe: "っへ",
      hho: "っほ",
      mma: "っま",
      mmi: "っみ",
      mmu: "っむ",
      mme: "っめ",
      mmo: "っも",
      yya: "っや",
      yyu: "っゆ",
      yyo: "っよ",
      rra: "っら",
      rri: "っり",
      rru: "っる",
      rre: "っれ",
      rro: "っろ",
      wwa: "っわ",
      gga: "っが",
      ggi: "っぎ",
      ggu: "っぐ",
      gge: "っげ",
      ggo: "っご",
      zza: "っざ",
      jji: "っじ",
      zzu: "っず",
      zze: "っぜ",
      zzo: "っぞ",
      dda: "っだ",
      ddi: "っぢ",
      ddu: "っづ",
      dde: "っで",
      ddo: "っど",
      bba: "っば",
      bbi: "っび",
      bbu: "っぶ",
      bbe: "っべ",
      bbo: "っぼ",
      ppa: "っぱ",
      ppi: "っぴ",
      ppu: "っぷ",
      ppe: "っぺ",
      ppo: "っぽ",
    },
    2: {
      a: "あ",
      i: "い",
      u: "う",
      e: "え",
      o: "お",
      ka: "か",
      ki: "き",
      ku: "く",
      ke: "け",
      ko: "こ",
      sa: "さ",
      shi: "し",
      su: "す",
      se: "せ",
      so: "そ",
      ta: "た",
      chi: "ち",
      tsu: "つ",
      te: "て",
      to: "と",
      na: "な",
      ni: "に",
      nu: "ぬ",
      ne: "ね",
      no: "の",
      ha: "は",
      hi: "ひ",
      fu: "ふ",
      he: "へ",
      ho: "ほ",
      ma: "ま",
      mi: "み",
      mu: "む",
      me: "め",
      mo: "も",
      ya: "や",
      yu: "ゆ",
      yo: "よ",
      ra: "ら",
      ri: "り",
      ru: "る",
      re: "れ",
      ro: "ろ",
      wa: "わ",
      wo: "を",
      n: "ん",
      ga: "が",
      gi: "ぎ",
      gu: "ぐ",
      ge: "げ",
      go: "ご",
      za: "ざ",
      ji: "じ",
      zu: "ず",
      ze: "ぜ",
      zo: "ぞ",
      da: "だ",
      di: "ぢ",
      du: "づ",
      de: "で",
      do: "ど",
      ba: "ば",
      bi: "び",
      bu: "ぶ",
      be: "べ",
      bo: "ぼ",
      pa: "ぱ",
      pi: "ぴ",
      pu: "ぷ",
      pe: "ぺ",
      po: "ぽ",
      xa: "ぁ",
      xi: "ぃ",
      xu: "ぅ",
      xe: "ぇ",
      xo: "ぉ",
      xya: "ゃ",
      xyu: "ゅ",
      xyo: "ょ",
      xtsu: "っ",
    },
  };

  Object.keys(romajiKanaTable).forEach((priority) => {
    Object.keys(romajiKanaTable[priority]).forEach((romaji) => {
      value = value.replace(romaji, romajiKanaTable[priority][romaji]);
    });
  });

  return value;
}
